apiVersion: perses.dev/v1alpha1
kind: PersesDashboard
metadata:
  name: openshift-gitops-multicluster
  namespace: perses-dev
spec:
  display:
    name: OpenShift GitOps - MultiCluster Overview
  duration: 1h
  layouts:
    - kind: Grid
      spec:
        display:
          title: GitOps Overview Stats
        items:
          - x: 0
            y: 0
            width: 4
            height: 3
            content:
              $ref: '#/spec/panels/0_0'
          - x: 4
            y: 0
            width: 4
            height: 3
            content:
              $ref: '#/spec/panels/0_1'
          - x: 8
            y: 0
            width: 4
            height: 3
            content:
              $ref: '#/spec/panels/0_2'
          - x: 12
            y: 0
            width: 4
            height: 3
            content:
              $ref: '#/spec/panels/0_3'
          - x: 16
            y: 0
            width: 4
            height: 3
            content:
              $ref: '#/spec/panels/0_4'
          - x: 20
            y: 0
            width: 4
            height: 3
            content:
              $ref: '#/spec/panels/0_5'
    - kind: Grid
      spec:
        display:
          title: GitOps Performance
        items:
          - x: 0
            y: 0
            width: 8
            height: 6
            content:
              $ref: '#/spec/panels/1_0'
          - x: 8
            y: 0
            width: 8
            height: 6
            content:
              $ref: '#/spec/panels/1_1'
          - x: 16
            y: 0
            width: 8
            height: 6
            content:
              $ref: '#/spec/panels/1_2'
  panels:
    '0_0':
      kind: Panel
      spec:
        display:
          name: Total Applications
        plugin:
          kind: StatChart
          spec:
            calculation: last
            format: { unit: decimal } # Added format, removed thresholds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'count(argocd_app_info{cluster=~"$cluster", project=~"$project", dest_namespace=~"$namespace"})'
    '0_1':
      kind: Panel
      spec:
        display:
          name: Healthy Applications
        plugin:
          kind: StatChart
          spec:
            calculation: last
            format: { unit: decimal } # Added format, removed thresholds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'count(argocd_app_info{health_status="Healthy", cluster=~"$cluster", project=~"$project", dest_namespace=~"$namespace"})'
    '0_2':
      kind: Panel
      spec:
        display:
          name: Degraded Applications
        plugin:
          kind: StatChart
          spec:
            calculation: last
            format: { unit: decimal } # Added format, removed thresholds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'count(argocd_app_info{health_status="Degraded", cluster=~"$cluster", project=~"$project", dest_namespace=~"$namespace"})'
    '0_3':
      kind: Panel
      spec:
        display:
          name: Progressing Applications
        plugin:
          kind: StatChart
          spec:
            calculation: last
            format: { unit: decimal } # Added format, removed thresholds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'count(argocd_app_info{health_status="Progressing", cluster=~"$cluster", project=~"$project", dest_namespace=~"$namespace"})'
    '0_4':
      kind: Panel
      spec:
        display:
          name: Synced Applications
        plugin:
          kind: StatChart
          spec:
            calculation: last
            format: { unit: decimal } # Added format, removed thresholds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'count(argocd_app_info{sync_status="Synced", cluster=~"$cluster", project=~"$project", dest_namespace=~"$namespace"})'
    '0_5':
      kind: Panel
      spec:
        display:
          name: OutOfSync Applications
        plugin:
          kind: StatChart
          spec:
            calculation: last
            format: { unit: decimal } # Added format, removed thresholds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'count(argocd_app_info{sync_status="OutOfSync", cluster=~"$cluster", project=~"$project", dest_namespace=~"$namespace"})'
    '1_0':
      kind: Panel
      spec:
        display:
          name: Application Sync Rate (ops/sec)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend: { mode: list, position: bottom, size: small } # Made more explicit
            visual: { display: line } # Added visual
            yAxis: { format: { unit: 'ops/sec' } } # Added explicit unit
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'sum by (cluster) (rate(argocd_app_sync_total{cluster=~"$cluster", project=~"$project"}[5m]))'
                  seriesNameFormat: '{{cluster}} - {{status}}'
    '1_1':
      kind: Panel
      spec:
        display:
          name: Avg App Reconciliation Duration (seconds)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend: { mode: list, position: bottom, size: small } # Made more explicit
            visual: { display: line } # Added visual
            yAxis: { format: { unit: seconds } } # Using 'seconds'
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'sum by (cluster) (rate(argocd_app_reconcile_sum{cluster=~"$cluster", project=~"$project"}[5m])) / sum by (cluster) (rate(argocd_app_reconcile_count{cluster=~"$cluster", project=~"$project"}[5m]))'
                  seriesNameFormat: '{{cluster}}'
    '1_2':
      kind: Panel
      spec:
        display:
          name: App Controller Queue Depth
        plugin:
          kind: TimeSeriesChart
          spec:
            legend: { mode: list, position: bottom, size: small } # Made more explicit
            visual: { display: line } # Added visual
            yAxis: { format: { unit: decimal } } # Added explicit unit
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource: { kind: PrometheusDatasource, name: prometheus-primary }
                  query: 'sum by (cluster) (workqueue_depth{queue="argocd_application_controller", cluster=~"$cluster"})'
                  seriesNameFormat: '{{cluster}}'
  variables:
    - kind: ListVariable
      spec:
        name: cluster
        allowMultiple: true
        allowAllValue: true
        plugin:
          kind: PrometheusLabelValuesVariable
          spec:
            datasource: { kind: PrometheusDatasource, name: prometheus-primary }
            labelName: cluster
            matchers: ['{__name__="argocd_app_info"}'] # Changed format
        display: { name: Cluster, hidden: false, sort: AscAlphabetical }
    - kind: ListVariable
      spec:
        name: project
        allowMultiple: true
        allowAllValue: true
        plugin:
          kind: PrometheusLabelValuesVariable
          spec:
            datasource: { kind: PrometheusDatasource, name: prometheus-primary }
            labelName: project
            matchers: ['{__name__="argocd_app_info", cluster=~"$cluster"}'] # Changed format
        display: { name: ArgoCD Project, hidden: false, sort: AscAlphabetical }
    - kind: ListVariable
      spec:
        name: namespace
        allowMultiple: true
        allowAllValue: true
        plugin:
          kind: PrometheusLabelValuesVariable
          spec:
            datasource: { kind: PrometheusDatasource, name: prometheus-primary }
            labelName: dest_namespace
            matchers: ['{__name__="argocd_app_info", cluster=~"$cluster", project=~"$project"}'] # Changed format
        display: { name: Application Namespace, hidden: false, sort: AscAlphabetical }
